---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/6/19 18:46
---

---@class Ability_Task_LeaveMainCameraState    退出主镜头状态
local Ability_Task_LeaveMainCameraState = UE4.Class(nil, "Ability_Task_LeaveMainCameraState")

function Ability_Task_LeaveMainCameraState:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_LeaveMainCameraState:OnTaskStartBP")
    if self.CameraName ~= "None" then
        UE4.USPGameCameraUtils.LeaveMainCameraStateCustomParam(self.CameraName)
    end
end

return Ability_Task_LeaveMainCameraState