---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/6/14 17:45
---
local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")
local SPLuaUtility = require("Feature.StarP.Script.System.SPLuaUtility")
local IsValid = UE4.UKismetSystemLibrary.IsValid
local ESPMaterialType = _SP.SPAbilityUtils.ESPMaterialType
local ELEMTypeEnum = _SPFeature.ServerEnum.SPPetElementType
local AttrEnum = _SPFeature.ServerEnum.StarPAttrType
local AttrOpEnum = _SPFeature.ServerEnum.StarPAttrOPType
local Ability_Task_MaterialEffect = UE4.Class(nil, "Ability_Task_MaterialEffect")

local INFINITE_TIME = 9999999999

local function Log(...)
    _SP.Log("SPAbility", "[Ability_Task_MaterialEffect]", ...)
end

function Ability_Task_MaterialEffect:OnTaskStartBP(Context)
    local ScratchPad = self:GetScratchPad(Context)
    if not ScratchPad then
        return
    end

    local TargetArray = UE4.TArray(UE4.AActor)
    self:GetActorsForTaskBP(Context, TargetArray)

    for i = 1, TargetArray:Length() do
        local Character = TargetArray:Get(i)
        if Character then
            self:GetMaterialConfig(Context, Character)
            if not IsValid(ScratchPad.ConfigMaterial) then
                return
            end
            local MaterialComponent = Character:GetComponentByClass(UE4.USPMaterialManagerComponent:StaticClass())
            local mesh = Character:GetComponentByClass(UE4.USkeletalMeshComponent.StaticClass())
            local Lifetime = (ScratchPad.ConfigMaterialParam and ScratchPad.ConfigMaterialParam:Length() > 0) and self:GetDuration() or INFINITE_TIME
            if mesh and MaterialComponent then
                table.insert(ScratchPad.MaterialComps, mesh)
                local Material = MaterialComponent:AddMaterial(ScratchPad.ConfigMaterial, ScratchPad.ConfigPriority, Lifetime, true)
                ScratchPad.Material = Material
            end

            if Character:IsA(UE4.ASPGameCharacterBase) and self.bAddWeaponMaterial then
                self:SetWeaponMaterial(Character, ScratchPad.ConfigMaterial)
            end

        end
    end
end

function Ability_Task_MaterialEffect:OnTaskEndBP(Context)
    local ScratchPad = self:GetScratchPad(Context)
    if not ScratchPad then
        return
    end

    local TargetArray = UE4.TArray(UE4.AActor)
    self:GetActorsForTaskBP(Context, TargetArray)
    for i = 1, TargetArray:Length() do
        local Character = TargetArray:Get(i)
        if Character then
            local MaterialComponent = Character:GetComponentByClass(UE4.USPMaterialManagerComponent:StaticClass())
            if MaterialComponent then
                MaterialComponent:SetMaterialLifeTime(ScratchPad.Material,0)
            end

            if Character:IsA(UE4.ASPGameCharacterBase) and self.bAddWeaponMaterial then
                self:SetWeaponMaterial(Character, nil)
            end
        end
    end
end

function Ability_Task_MaterialEffect:GetMaterialConfig(Context, Character)
    local ScratchPad = self:GetScratchPad(Context)
    if not ScratchPad then
        return
    end
    if self.bUseElementMaterial then
        local Element = nil
        if Character:IsA(UE4.ASPGameMonsterBase) then
            local MonsterConfig = Character.GetMonsterTypeConfig and Character:GetMonsterTypeConfig() or nil
            if MonsterConfig ~= nil and MonsterConfig.elements ~= nil then
                Element = ELEMTypeEnum[MonsterConfig.elements]
            end
        elseif Character:IsA(UE4.ASPGameCharacterBase) then
            local AttrComponent = _SP.SPSubSystemUtil.GetAttributeDataByAvatar(Character)
            if AttrComponent == nil then
                return nil
            end
            if _SP.IsDSorStandalone then
                Element = AttrComponent:GetSPAttributeValue(AttrEnum.SPAT_Ultimate_DamageElementType, AttrOpEnum.SPAT_OP_Base)
            else
                Element = AttrComponent:GetAttributeValue(AttrEnum.SPAT_Ultimate_DamageElementType)
            end
        end

        if Element then
            local MaterialConfigs = self.ElementMaterials:ToTable()
            if MaterialConfigs then
            local MaterialConfig = MaterialConfigs[Element]
                if (MaterialConfig) then
                    ScratchPad.ConfigMaterial = MaterialConfig.Material
                    ScratchPad.ConfigPriority = MaterialConfig.Priority
                    ScratchPad.ConfigMaterialParam = MaterialConfig.ChangeMaterialParams
                end
            end
        end

    else
        ScratchPad.ConfigMaterial = self.Material
        ScratchPad.ConfigPriority = self.Priority
        ScratchPad.ConfigMaterialParam = self.ChangeMaterialParams
    end

end

function Ability_Task_MaterialEffect:GetCurrentCurveValue(currentTime, curve, type)
    local DurationTime = self:GetDuration()
    local Progress = DurationTime > 0 and (currentTime / DurationTime) or 0
    if type == ESPMaterialType.Float and curve:IsA(UE4.UCurveFloat.StaticClass()) then
        return curve:GetFloatValue(Progress)
    elseif type == ESPMaterialType.LinearColor and curve:IsA(UE4.UCurveLinearColor.StaticClass()) then
        return curve:GetLinearColorValue(Progress)
    end
end

function Ability_Task_MaterialEffect:SetMaterialParamByType(mat, paramName, value, modifyType)
    if not _SP.IsValid(mat) then
        Log("mat nil")
        return
    end
    if modifyType == ESPMaterialType.Float and type(value) == "number" then
        if mat.SetScalarParameterValue then
            if value <= 0.00001 then
                value = 0
            end
            mat:SetScalarParameterValue(paramName, value)
        end
    elseif modifyType == ESPMaterialType.LinearColor then
        if mat.SetVectorParameterValue then
            mat:SetVectorParameterValue(paramName, value)
        end
    end
end

function Ability_Task_MaterialEffect:OnTaskTickBP(Context, DeltaTime)
    if not self.bUpdateParam then
        return
    end
    local ScratchPad = self:GetScratchPad(Context)
    if not ScratchPad then
        return
    end
    ScratchPad.ElapsedTime = ScratchPad.ElapsedTime + DeltaTime
    -- Tick Modify Material Param
    local paramName, param
    local curve, curveType
    local overlayMaterial
    for _, materialComp in pairs(ScratchPad.MaterialComps) do
        if _SP.IsValid(materialComp) and materialComp.GetOverlayMaterial then
            overlayMaterial = materialComp:GetOverlayMaterial()
            if overlayMaterial and ScratchPad.ConfigMaterialParam then
                for i = 1, ScratchPad.ConfigMaterialParam:Length() do
                    param = ScratchPad.ConfigMaterialParam:GetRef(i)
                    curve = param.Curve
                    curveType = param.Type
                    local value = self:GetCurrentCurveValue(ScratchPad.ElapsedTime, curve, curveType)
                    if value then
                        paramName = param.ParamName
                        if paramName and paramName ~= "" then
                            -- overlayMaterial:SetScalarParameterValue(paramName, value)
                            self:SetMaterialParamByType(overlayMaterial, paramName, value, curveType)
                        end
                    end
                end
            end
        end
    end
end

function Ability_Task_MaterialEffect:SetWeaponMaterial(Character, Material)
    if Character.GetCrtEquipWeapon ~= nil then
        local weapon = Character:GetCrtEquipWeapon()
        if UE4.UKismetSystemLibrary.IsValid(weapon) then
            if weapon:IsA(UE4.ASPDualWeapon) then
                local LeftWeapon = weapon.LeftWeapon
                local RightWeapon = weapon.RightWeapon
                if _SP.IsValid(LeftWeapon) and _SP.IsValid(RightWeapon) then
                    local LeftMeshComp = LeftWeapon:GetWeaponMeshComponent()
                    local RightMeshComp = RightWeapon:GetWeaponMeshComponent()
                    if LeftMeshComp and RightMeshComp then
                        LeftMeshComp:SetOverlayMaterial(Material)
                        RightMeshComp:SetOverlayMaterial(Material)
                    end
                end
            else
                local MeshComp = weapon:GetWeaponMeshComponent()
                if MeshComp then
                    MeshComp:SetOverlayMaterial(Material)
                end
            end
        end
    end
end

function Ability_Task_MaterialEffect:IsSingleFrameBP()
    return not self.bUpdateParam
end

function Ability_Task_MaterialEffect:ResetScratchPadBP(ScratchPad)
    if ScratchPad then
        ScratchPad.MaterialComps = {}
        ScratchPad.ElapsedTime = 0
        ScratchPad.Material = nil
        ScratchPad.ConfigMaterial = nil
        ScratchPad.ConfigPriority = nil
        ScratchPad.ConfigMaterialParam = nil
    end
end

function Ability_Task_MaterialEffect:GetTaskScratchPadClassBP(Context)
    return SPAbilityUtils.LoadScratchPadClass(SPAbility.ScratchPadClass.MaterialEffect)
end

return Ability_Task_MaterialEffect