---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/6/18 23:53
---
local Ability_Task_LaserWeaponPad = UE4.Class(nil, "Ability_Task_LaserWeaponPad")

--[[
]]

return Ability_Task_LaserWeaponPad