---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/6/12 0:01
---
local Ability_Task_PlaceHolder = UE4.Class(nil, "Ability_Task_PlaceHolder")

function Ability_Task_PlaceHolder:IsSingleFrameBP()
    return false
end

function Ability_Task_PlaceHolder:GetTaskRealmBP()
    return UE4.EAbleAbilityTaskRealm.ATR_ClientAndServer
end

return Ability_Task_PlaceHolder