---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hangtian.
--- DateTime: 2024/6/18 下午7:58
---

local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")

local function ErrLog(...)
    _SP.LogError("SPAbility", "Ability_Task_AttachActorToOwner", ...)
end

local function Log(...)
    _SP.Log("SPAbility", "Ability_Task_AttachActorToOwner", ...)
end
---@class Ability_Task_AttachActorToOwner
---@field DecorateTarget EAbleAbilityTargetType
---@field AttachTarget EAbleAbilityTargetType
---@field AttachSocket string
---@field DecorationRelativeTransform FTransform
local Ability_Task_AttachActorToOwner = UE4.Class(nil, "Ability_Task_AttachActorToOwner")

---@param Context UAblAbilityContext
function Ability_Task_AttachActorToOwner:OnTaskStartBP(Context)
    Log("OnTaskStartBP")
    local DecorationActor = self:GetSingleActorFromTargetTypeBP(Context, self.DecorateTarget)
    if not DecorationActor then
        return
    end

    local DecorationMeshComponent = DecorationActor:GetComponentByClass(UE4.USkeletalMeshComponent.StaticClass())
    if not DecorationMeshComponent then
        return
    end

    local DecorationMovementComponent = DecorationActor:GetComponentByClass(UE4.UCharacterMovementComponent.StaticClass())
    if not DecorationMovementComponent then
        return
    end

    local CapsuleComponent = DecorationActor:GetComponentByClass(UE4.UCapsuleComponent.StaticClass())
    if not CapsuleComponent then
        return
    end

    local AttachActor = self:GetSingleActorFromTargetTypeBP(Context, self.AttachTarget)
    if not AttachActor then
        return
    end

    local AttachSkeletonMeshComponent = AttachActor:GetComponentByClass(UE4.USkeletalMeshComponent.StaticClass());
    if not AttachSkeletonMeshComponent then
        return
    end

    if DecorationActor:Cast(UE4.ASPGameMonsterBase.StaticClass()) then
        DecorationActor:SPSetActorLogicallyHidden(true)
        DecorationActor:SPSetActorPhysicallyHidden(true)
        if self.IsNeedHideMesh then
            DecorationActor:SPSetActorVisuallyHidden(true)
        end
    end
    -- 在上面已经设置了相关碰撞
    --DecorationMeshComponent:SetCollisionEnabled(UE4.ECollisionEnabled.NoCollision)
    --CapsuleComponent:SetCollisionEnabled(UE4.ECollisionEnabled.NoCollision)
    UE4.USPGameLibrary.SetActiveCharMovement(DecorationMovementComponent, DecorationActor, false);

    -- 仅在客户端设置Attach
    if _SP.IsClient then
        -- 缓存DecorationActor的Scale，以便在Detach时恢复
        if self.bRestoreActorScaleOnEnd then
            local ScratchPad = self:GetScratchPad(Context)
            if _SP.IsValid(ScratchPad) then
                ScratchPad.CachedActorScale = DecorationActor:GetActorScale3D()
            else
                Log("OnTaskStartBP Failed to retreive ScratchPad!")
            end
        end

        local InverseTrs = self.DecorationRelativeTransform * DecorationMeshComponent:GetRelativeTransform():Inverse();
        DecorationActor:K2_AttachToComponent(AttachSkeletonMeshComponent,
                self.AttachSocket,
                UE4.EAttachmentRule.KeepWorld,
                UE4.EAttachmentRule.KeepWorld,
                UE4.EAttachmentRule.KeepWorld, false)
        DecorationActor:K2_SetActorRelativeTransform(InverseTrs);
    end
end
---@param Context UAblAbilityContext
function Ability_Task_AttachActorToOwner:OnTaskEndBP(Context)
    Log("OnTaskEndBP")

    local DecorationActor = self:GetSingleActorFromTargetTypeBP(Context, self.DecorateTarget)
    if not DecorationActor then
        return
    end

    local DecorationMeshComponent = DecorationActor:GetComponentByClass(UE4.USkeletalMeshComponent.StaticClass())
    if not DecorationMeshComponent then
        return
    end

    local DecorationMovementComponent = DecorationActor:GetComponentByClass(UE4.UCharacterMovementComponent.StaticClass())
    if not DecorationMovementComponent then
        return
    end

    local CapsuleComponent = DecorationActor:GetComponentByClass(UE4.UCapsuleComponent.StaticClass())
    if not CapsuleComponent then
        return
    end

    DecorationMeshComponent:SetCollisionEnabled(UE4.ECollisionEnabled.QueryAndPhysics)
    CapsuleComponent:SetCollisionEnabled(UE4.ECollisionEnabled.QueryAndPhysics)
    UE4.USPGameLibrary.SetActiveCharMovement(DecorationMovementComponent, DecorationActor, true);

    -- 仅在客户端设置Attach
    if _SP.IsClient then
        DecorationActor:K2_DetachFromActor(UE4.EDetachmentRule.KeepWorld, UE4.EDetachmentRule.KeepWorld, UE4.EDetachmentRule.KeepWorld)
        -- 客户端上先把Actor旋转设置为0，否则再收到DS的同步前可能会呈现奇怪的角度
        DecorationActor:K2_SetActorRotation(UE4.FRotator(0, 0, 0))

        -- Detach结束后恢复DecorationActor的Scale
        if self.bRestoreActorScaleOnEnd then
            local ScratchPad = self:GetScratchPad(Context)
            if _SP.IsValid(ScratchPad) then
                DecorationActor:SetActorScale3D(ScratchPad.CachedActorScale)
            else
                Log("OnTaskEndBP Failed to retreive ScratchPad!")
            end
        end
    end
end

function Ability_Task_AttachActorToOwner:ResetScratchPadBP(ScratchPad)
    if _SP.IsValid(ScratchPad) then
        ScratchPad.CachedActorScale = UE4.FVector(1, 1, 1)
    end
end

function Ability_Task_AttachActorToOwner:GetTaskScratchPadClassBP(Context)
    return SPAbilityUtils.LoadScratchPadClass(SPAbility.ScratchPadClass.AttachActorToOwner)
end

return Ability_Task_AttachActorToOwner