---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hangtian.
--- DateTime: 2024/6/17 下午7:45
---

local function ErrLog(...)
    _SP.LogError("SPAbility","Ability_Task_LeaveCharState", ...)
end

local function Log(...)
    _SP.Log("SPAbility","Ability_Task_LeaveCharState", ...)
end

local Ability_Task_LeaveCharState = UE4.Class(nil, "Ability_Task_LeaveCharState")
---@param Context UAblAbilityContext
function Ability_Task_LeaveCharState:OnTaskStartBP(Context)
    Log("OnTaskStartBP")
    if self.m_TaskTargets == nil then
        return
    end
    local len = self.m_TaskTargets:Length()
    for iter = 1, len do
        local TargetType = self.m_TaskTargets:Get(iter)
        local TargetActor = self:GetSingleActorFromTargetTypeBP(Context, TargetType)
        if TargetActor ~= nil and TargetActor:Cast(UE4.ASPGameCharacterBase) then
            if self.IsSPState then
                if self.Realm == UE4.EAbleAbilityTaskRealm.ATR_Client then
                    TargetActor:TryLeaveActionState_New(self.SPLeaveActionState, UE4.EStateIdOffsetType.SP, false)
                else
                    TargetActor:TryLeaveActionState_New(self.SPLeaveActionState, UE4.EStateIdOffsetType.SP, true)
                end
            else
                if self.Realm == UE4.EAbleAbilityTaskRealm.ATR_Client then
                    TargetActor:TryLeaveActionState_New(self.LeaveActionState, UE4.EStateIdOffsetType.Default, false)
                else
                    TargetActor:TryLeaveActionState_New(self.LeaveActionState, UE4.EStateIdOffsetType.Default, true)
                end
            end
        end
    end
end

function Ability_Task_LeaveCharState:OnTaskEndBP(Context)
    Log("OnTaskEndBP")
end

return Ability_Task_LeaveCharState