---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/5/1 15:30
---

---@class Ability_Task_CollisionDamagePad : USPAbilityTaskScratchPad
local Ability_Task_CollisionDamagePad = UE4.Class(nil, "Ability_Task_CollisionDamagePad")

return Ability_Task_CollisionDamagePad