---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/5/31 18:57
---
local Ability_Task_ModifyAttributePad = UE4.Class(nil, "Ability_Task_ModifyAttributePad")

return Ability_Task_ModifyAttributePad