---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/6/17 20:27
---

---@class Ability_Task_FireAgain    再次开火（用于伙伴技能后摇阶段，打断当前技能，再次执行开火）
local Ability_Task_FireAgain = UE4.Class(nil, "Ability_Task_FireAgain")

function Ability_Task_FireAgain:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask","Ability_Task_FireAgain:OnTaskStartBP")
    self.bIsPressFireBtn = false
    self.bEnableTick = true
    local Character = Context:GetOwner()
    if Character then
        self.CharInventoryComp = Character:SafeGetInventoryComponent()
        if self.CharInventoryComp then
            self.bIsPressFireBtn = self.CharInventoryComp.bIsPressFireBtn
        end
    end
end

function Ability_Task_FireAgain:OnTaskTickBP(Context)
    if not self.bEnableTick then
        return
    end
    if self.CharInventoryComp then
        if self.bIsPressFireBtn then
            --初始按下状态则检查一次松开
            if not self.CharInventoryComp.bIsPressFireBtn then
                self.bIsPressFireBtn = false
            end
        else
            if self.CharInventoryComp.bIsPressFireBtn then
                self.bIsPressFireBtn = true
            end
        end
    end
    if self.bIsPressFireBtn then
        self.bEnableTick = false
        self:FireAgain(Context)
    end
end

function Ability_Task_FireAgain:FireAgain(Context)
    if self.CharInventoryComp then
        local AbilityId = Context:GetAbilityId()
        local AbilityComp = Context:GetSelfAbilityComponent()
        if AbilityId and AbilityComp then
            AbilityComp:InterruptedAbility(AbilityId, "task fire again")
            _SP.Log("SPAbilityTask", "Ability_Task_FireAgain:InterruptAbility AbilityId: ", AbilityId)
            local crtWeapon = self.CharInventoryComp:GetCrtEquipWeapon()
            if _SP.IsValid(crtWeapon) then
                crtWeapon:LeaveWeaponFiringCharacterState()
            end
            self.CharInventoryComp:RespBeginFire()
        end
    end
end

return Ability_Task_FireAgain