---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/4/26 15:13
---
local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")
local Ability_Task_Template = UE4.Class(nil, "Ability_Task_Template")

function Ability_Task_Template:OnTaskStartBP(Context)
    -- Get ScratchPad
    local ScratchPad = self:GetScratchPad(Context)
    if ScratchPad then
        ScratchPad.LogText = self.LogText
        print("Ability_Task_Template:OnTaskStartBP !!!", self.LogText)
    end

    -- Get Target
    local Target = self:GetSingleActorFromTargetTypeBP(Context, UE4.EAbleAbilityTargetType.ATT_Self)
    -- or
    --[[
    local TargetArray = UE4.TArray(UE4.AActor)
    self:GetActorsForTaskBP(Context, TargetArray)
    local Target = TargetArray:Num() > 0 and TargetArray:Get(1) or nil
    ]]

    if Target then
        print("Target Display Name = ", Target:GetName())
    end
end

function Ability_Task_Template:OnTaskEndBP(Context)
    local ScratchPad = self:GetScratchPad(Context)
    if ScratchPad then
        print("Ability_Task_Template:OnTaskEndBP !!!", ScratchPad.LogText)
    end
end

function Ability_Task_Template:IsSingleFrameBP()
    return true
end

function Ability_Task_Template:ResetScratchPadBP(ScratchPad)
    if ScratchPad then
        ScratchPad.LogText = nil
    end
end

function Ability_Task_Template:GetTaskScratchPadClassBP(Context)
    return SPAbilityUtils.LoadScratchPadClass(SPAbility.ScratchPadClass.TemplatePad)
end

return Ability_Task_Template