---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/11/18 16:40
---
local Ability_Task_PlayAbility = UE4.Class(nil, "Ability_Task_PlayAbility")
local SPLuaUtility = require("Feature.StarP.Script.System.SPLuaUtility")

function Ability_Task_PlayAbility:IsSingleFrameBP()
    return true
end

function Ability_Task_PlayAbility:GetTaskRealmBP()
    return UE4.EAbleAbilityTaskRealm.ATR_Server
end

---@param Context UAbleAbilityContext
function Ability_Task_PlayAbility:OnTaskStartBP(Context)
    if self.AbilityId <= 0 then
        return
    end

    -- local AbilityDataTable = {}
    -- local Ret = SPLuaUtility:GetSkillInfo_Lua(self.AbilityId, AbilityDataTable)
    local AbilityDataTable, isPassive = _SP.SPGameplayUtils:GetSkillData(self.AbilityId)
    if not AbilityDataTable then
        return
    end

    local TargetArray = UE4.TArray(UE4.AActor)
    self:GetActorsForTaskBP(Context, TargetArray)

    for i = 1, TargetArray:Length() do
        local Target = TargetArray:Get(i)
        if Target then
            ---@type USPAbilityComponent
            local AbilityComponent = Target:GetComponentByClass(UE4.USPAbilityComponent:StaticClass())
            if AbilityComponent then
                AbilityComponent:TryActivateAbility(self.AbilityId, Target, Context:GetOwner())
            end
        end
    end
end

return Ability_Task_PlayAbility