---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/11/20 15:54
---

---@class Ability_Task_WeaponFire : UAbleAbilityTask 武器开火
local Ability_Task_WeaponFire = UE4.Class(nil, "Ability_Task_WeaponFire")

function Ability_Task_WeaponFire:OnTaskStartBP(Context)
    self.LastShootTime = 0
    self.bEnableTick = self:IsKeepFiring() or false
    local Character = Context:GetOwner()
    if _SP.IsValid(Character) then
        self.CurrentWeapon = Character:GetCrtEquipWeapon() or nil
    end
    self:OnSingleShoot(Context)
end

function Ability_Task_WeaponFire:OnTaskTickBP(Context)
    if not self.bEnableTick then
        return
    end

    local curTime = UE4.UGameplayStatics.GetTimeSeconds(_SP.GetCurrentWorld())
    if (curTime - self.LastShootTime) >= self.FireInterval then
        self:OnSingleShoot(Context)
    end
end

function Ability_Task_WeaponFire:OnTaskEndBP(Context, Result)
    self.CurrentWeapon = nil
end

function Ability_Task_WeaponFire:OnSingleShoot(Context)
    self.LastShootTime = UE4.UGameplayStatics.GetTimeSeconds(_SP.GetCurrentWorld())
    if self:IsValidWeapon() then
        self.CurrentWeapon:Shooting()
    end
end

function Ability_Task_WeaponFire:IsKeepFiring()
    return self.FireInterval > 0
end

function Ability_Task_WeaponFire:IsValidWeapon()
    return self.CurrentWeapon and _SP.IsValid(self.CurrentWeapon) and self.CurrentWeapon.Shooting
end

return Ability_Task_WeaponFire
