---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sakuragong.
--- DateTime: 2024/5/28 11:26
---
local Ability_Task_VoicePad = UE4.Class(nil, "Ability_Task_VoicePad")

return Ability_Task_VoicePad