---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/7/5 13:35
---

---@class Ability_Task_ManualRefreshAnimClass    刷新角色ABP
local Ability_Task_ManualRefreshAnimClass = UE4.Class(nil, "Ability_Task_ManualRefreshAnimClass")

function Ability_Task_ManualRefreshAnimClass:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask","Ability_Task_ManualRefreshAnimClass:OnTaskStartBP")
    local Character = self:GetSingleActorFromTargetTypeBP(Context, UE4.EAbleAbilityTargetType.ATT_TargetActor)
    if Character then
        self.CharInventoryComp = Character:SafeGetInventoryComponent()
        if self.CharInventoryComp then
            self.CharInventoryComp:ManualRefreshAnimClass()
        end
    end
end

return Ability_Task_ManualRefreshAnimClass