---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/1/18 23:05
---

---@class Ability_Task_StopCameraAdjust
local Ability_Task_StopCameraAdjust = UE4.Class(nil, "Ability_Task_StopCameraAdjust")

function Ability_Task_StopCameraAdjust:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_StopCameraAdjust:OnTaskStartBP")
    if self:IsLocalCharacter(Context) then
        UE4.USPGameCameraUtils:TryLeaveSkillTaskState()
    end
end

function Ability_Task_StopCameraAdjust:IsLocalCharacter(Context)
    if _SPFeature.Utils.WorldUtils:IsStandalone() then
        return true
    end
    local Character = Context:GetOwner()
    if Character then
        return Character:IsLocallyControlled()
    end
    return false
end

return Ability_Task_StopCameraAdjust