---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by
--- DateTime: 2024/8/8 19:30
---
local Ability_Task_RemoveAllDebuffPad = UE4.Class(nil, "Ability_Task_RemoveAllDebuffPad")

--[[
    ---@type UE4.UShapeComponent
    CollisionComponent = nil

    ---@type table[UE4.UPrimitiveComponent, table]
    OverlappingComponents = {}

    ---@type number
    Timespan = 0

    ---@type {}
    AddBuffActors
]]

return Ability_Task_RemoveAllDebuffPad