---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/12/21 14:46
---

local MeleeType = UE4.EBattleAssistCtrlWeaponType.Meleen
local GunType = UE4.EBattleAssistCtrlWeaponType.Gun
local WandType = UE4.EBattleAssistCtrlWeaponType.Wand

---@class Ability_Task_StartBattleTurn  开启战斗镜头
local Ability_Task_StartBattleTurn = UE4.Class(nil, "Ability_Task_StartBattleTurn")

---OnTaskStartBP
---@param Context table
function Ability_Task_StartBattleTurn:OnTaskStartBP(Context)
    if not self:IsLocalCharacter(Context) then
        return
    end

    local character = Context:GetOwner()
    if not _SP.IsValid(character) then
        return
    end

    if not character:IsA(UE4.ASPGameCharacterBase) then
        return
    end

    local targetActor = self:GetSingleActorFromTargetTypeBP(Context, self.TargetType)
    if not _SP.IsValid(targetActor) then
        return
    end

    local crtWeapon = character:GetCrtEquipWeapon()
    if not _SP.IsValid(crtWeapon) then
       return
    end

    local WeaponConf = _SP.SPConfigManager:GetConfigById("FPSWeaponTable", "FPSWeaponClientConf", crtWeapon.weaponId)
    if WeaponConf == nil then
        _SP.Log("SPAbility", "Ability_Task_StartBattleTurn:StartBattleAssistCtrlTurnWithLimitAngle WeaponConf is nil.")
        return
    end

    local weaponType = nil
    local weaponTalentGroup = WeaponConf.weaponTalentGroup
    for _, typeId in pairs(weaponTalentGroup) do
        if typeId == MeleeType or typeId == GunType or typeId == WandType then
            -- TODO 临时写法，待策划明确更好的方式
            weaponType = typeId
            break
        end
    end

    if not weaponType then
        _SP.Log("SPAbility", "Ability_Task_StartBattleTurn:StartBattleAssistCtrlTurnWithLimitAngle weaponType is nil.")
        return
    end

    _SP.Log("SPAbility", "Ability_Task_StartBattleTurn:StartBattleAssistCtrlTurnWithLimitAngle")
    if self.bCustom then
        UE4.USPGameCameraUtils.StartBattleAssistCtrlTurnCustomParam(targetActor, self.TurnTime, weaponType, self.CustomParam)
    else
        UE4.USPGameCameraUtils.StartBattleAssistCtrlTurn(targetActor, self.TurnTime, weaponType)
    end
end

function Ability_Task_StartBattleTurn:IsLocalCharacter(Context)
    if _SPFeature.Utils.WorldUtils:IsStandalone() then
        return true
    end
    local Character = Context:GetOwner()
    if Character then
        return Character:IsLocallyControlled()
    end
    return false
end

return Ability_Task_StartBattleTurn