---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/5/29 15:39
---

---@class Ability_Task_SetEightDirectionMove    设置八方向移动
local Ability_Task_SetEightDirectionMove = UE4.Class(nil, "Ability_Task_SetEightDirectionMove")

function Ability_Task_SetEightDirectionMove:OnTaskStartBP(Context)
	print("Ability_Task_SetEightDirectionMove:OnTaskStartBP")
	self.AnimStateComp = nil
	local Player = Context:GetOwner()
	if Player then
		self.AnimStateComp = Player:GetComponentByClass(UE4.USPAnimStateComponent.StaticClass())
		self:CheckTargetToSetEightDirection(Context)
	end
end

function Ability_Task_SetEightDirectionMove:OnTaskEndBP(Context)
	-- print("Ability_Task_SetEightDirectionMove:OnTaskEndBP")
	if self.AnimStateComp then
		self.AnimStateComp:SetUseEightDirection(false)
	end
end

function Ability_Task_SetEightDirectionMove:CheckTargetToSetEightDirection(Context)
	if self.AnimStateComp then
		local bUseEightDirection = not self.bCheckTarget;
		if (self.bCheckTarget) then
			local TargetActor = self:GetSingleActorFromTargetTypeBP(Context, self.TargetType)
			if TargetActor then
				local TaskTargets = UE4.TArray(UE4.AActor)
				self:GetActorsForTaskBP(Context, TaskTargets)
				if TaskTargets and TaskTargets:Length() > 0 then
					-- print("Ability_Task_SetEightDirectionMove:CheckTargetToSetEightDirection true")
					bUseEightDirection = true
				end
			end
		end
		self.AnimStateComp:SetUseEightDirection(bUseEightDirection);
	end
end

return Ability_Task_SetEightDirectionMove