---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/6/17 16:01
---

---@class Ability_Task_BackLock    锁背
local Ability_Task_BackLock = UE4.Class(nil, "Ability_Task_BackLock")

function Ability_Task_BackLock:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_BackLock:OnTaskStartBP")
    local Character = Context:GetOwner()
    self.IsMonster = false
    self.Player = nil
    self.AnimStateComp = nil
    if Character then
        if Character:Cast(UE4.ASPGameMonsterBase) then
            self.IsMonster = true
        end
        if self.IsMonster then
            self.Player = Character:FindRelatedPlayerPawn()
        else
            self.Player = Character
            self.AnimStateComp = Character:GetComponentByClass(UE4.USPAnimStateComponent.StaticClass())
            self:SetEightDirection(true)
        end
    end

    if self.Player then
        UE4.USPGameCameraUtils.EnableAimState(true, self.Player, UE4.EMoeSPInputSensitiveType.RangeWeapon)
    end
end

function Ability_Task_BackLock:OnTaskEndBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_BackLock:OnTaskEndBP")
    if self.Player then
        UE4.USPGameCameraUtils.EnableAimState(false, self.Player, UE4.EMoeSPInputSensitiveType.RangeWeapon)
    end
    if not self.IsMonster then
        self:SetEightDirection(false)
    end
end

function Ability_Task_BackLock:SetEightDirection(IsEnable)
    if self.AnimStateComp then
        self.AnimStateComp:SetUseEightDirection(IsEnable)
    end
end

return Ability_Task_BackLock