---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/1/21 0:01
---

---@class Ability_Task_WeaponCharging : UAbleAbilityTask 武器蓄力
local Ability_Task_WeaponCharging = UE4.Class(nil, "Ability_Task_WeaponCharging")

function Ability_Task_WeaponCharging:OnTaskStartBP(Context)
    local Character = Context:GetOwner()
    if _SP.IsValid(Character) then
        self.CurrentWeapon = Character:GetCrtEquipWeapon() or nil
        if _SP.IsValid(self.CurrentWeapon) and self.CurrentWeapon.BeginCharging then
            self.CurrentWeapon:BeginCharging()
        end
    end
end

function Ability_Task_WeaponCharging:OnTaskEndBP(Context, Result)
    if _SP.IsValid(self.CurrentWeapon) and self.CurrentWeapon.EndCharging then
        self.CurrentWeapon:EndCharging()
    end
end

return Ability_Task_WeaponCharging