---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by benedictge.
--- DateTime: 2024/9/24 14:48
---

local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")
local Ability_Task_SetBallInHandVisibility = UE4.Class(nil, "Ability_Task_SetBallInHandVisibility")



function Ability_Task_SetBallInHandVisibility:OnTaskStartBP(Context)
    local TargetActor = self:GetSingleActorFromTargetTypeBP(Context, self.TargetType)
    if TargetActor == nil then
        return
    end
    local Player = TargetActor:Cast(UE4.ASPGameCharacterBase)
    if _SP.IsValid(Player) then
        local CaptureComp = Player:GetCaptureComponent()
        if _SP.IsValid(CaptureComp) then
            CaptureComp:SetCaptureBallInHandVisibility(self.NewVisibility)
        end
    end
end








return Ability_Task_SetBallInHandVisibility