---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/2/17 17:25
---

---@class Ability_Task_SetWeaponTargetActorPad    设置武器目标Pad
local Ability_Task_SetWeaponTargetActorPad = UE4.Class(nil, "Ability_Task_SetWeaponTargetActorPad")

return Ability_Task_SetWeaponTargetActorPad