---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/11/7 19:57
---

---@class Ability_Task_PetWeapon_SetShootState 设置伙伴武器射击参数
local Ability_Task_PetWeapon_SetShootState = UE4.Class(nil, "Ability_Task_PetWeapon_SetShootState")

function Ability_Task_PetWeapon_SetShootState:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_PetWeapon_SetShootState:OnTaskStartBP")
    self.Character = Context:GetOwner()
    if _SP.IsValid(self.Character) then
        local CurrentWeapon = self.Character:GetCrtEquipWeapon()
        if _SP.IsValid(CurrentWeapon) then
            self.MainWeaponSkeletalMeshComponent = CurrentWeapon:GetWeaponSkeletalMeshComponent()
            if self.MainWeaponSkeletalMeshComponent then
                self.WeaponAnimInst = self.MainWeaponSkeletalMeshComponent:GetAnimInstance()
            end
            if self.WeaponAnimInst then
                if self.WeaponAnimInst.SetShootState then
                    self.WeaponAnimInst:SetShootState(self.bShootState)
                end
                if self.WeaponAnimInst.SetShootEnd then
                    self.WeaponAnimInst:SetShootEnd(self.bShootEnd)
                end
            end
        end
    end
end

function Ability_Task_PetWeapon_SetShootState:OnTaskEndBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_PetWeapon_SetShootState:OnTaskEndBP")
    if not self.IsSingleFrame then
        if self.bResetOnEnd then
            if self.WeaponAnimInst then
                if self.WeaponAnimInst.SetShootState then
                    self.WeaponAnimInst:SetShootState(false)
                end
                if self.WeaponAnimInst.SetShootEnd then
                    self.WeaponAnimInst:SetShootEnd(false)
                end
            end
        end
    end
end

return Ability_Task_PetWeapon_SetShootState