---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by actorwang.
--- DateTime: 2024/12/17 20:46
---
local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")
local SPLuaUtility = require("Feature.StarP.Script.System.SPLuaUtility")
local Ability_Task_SPCameraYawReset = UE4.Class(nil, "Ability_Task_SPCameraYawReset")

local IsValid = UE4.UKismetSystemLibrary.IsValid

function Ability_Task_SPCameraYawReset:OnTaskStartBP(Context)
    if not self:IsLocalCharacter(Context) then
        return
    end
    if not self.FadeTime or not self.CustomYaw or self.FadeTime <= 0 then
        return
    end
    UE4.USPGameCameraUtils.BeginYawResetByCustomParam(self.CustomYaw, self.FadeTime)
end

function Ability_Task_SPCameraYawReset:OnTaskEndBP(Context)
    
end


function Ability_Task_SPCameraYawReset:IsLocalCharacter(Context)
    if _SPFeature.Utils.WorldUtils:IsStandalone() then
        return true
    end
    local Character = Context:GetOwner()
    if Character then
        return Character:IsLocallyControlled()
    end
    return false
end

return Ability_Task_SPCameraYawReset