---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/6/14 17:45
---
local Ability_Task_ModifyAttributePad = UE4.Class(nil, "Ability_Task_ModifyAttributePad")

--[[
    ---@type number
    local Handle = 0
]]

return Ability_Task_ModifyAttributePad