---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ecoliwu.
--- DateTime: 2024/6/22 15:49
---
local Ability_Task_CollisionChannelsPad = UE4.Class(nil, "Ability_Task_CollisionChannelsPad")

return Ability_Task_CollisionChannelsPad