---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hangtian.
--- DateTime: 2024/6/18 下午5:27
---

local function ErrLog(...)
    _SP.LogError("SPAbility", "Ability_Task_SetTargetLocationToSummon", ...)
end

local function Log(...)
    _SP.Log("SPAbility", "Ability_Task_SetTargetLocationToSummon", ...)
end
local SPGameplayUtils = require("Feature.StarP.Script.System.SPGameplayUtils")

---@class Ability_Task_SetTargetLocationToSummon
local Ability_Task_SetTargetLocationToSummon = UE4.Class(nil, "Ability_Task_SetTargetLocationToSummon")

---@param Context UAblAbilityContext
function Ability_Task_SetTargetLocationToSummon:OnTaskStartBP(Context)
    Log("OnTaskStartBP")
    if Context == nil then
        return UE4.EAbleConditionResults.ACR_Passed
    end
    local Character = Context:GetOwner()
    if _SP.IsValid(Character) then
        local SummonInfo = _SP.SPGameAbilityManager:GetTargetSummonInfo(Character, self.SummonID)
        if SummonInfo ~= nil and _SP.IsValid(SummonInfo["SummonActor"]) then
            local Summon = SummonInfo["SummonActor"]
            local Location = Summon:K2_GetActorLocation()
            Context:SetTargetLocation(Location)
        end
    end
end

return Ability_Task_SetTargetLocationToSummon