---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/4/26 15:16
---
local Ability_Task_PlayerCameraAdjustPad = UE4.Class(nil, "Ability_Task_PlayerCameraAdjustPad")

return Ability_Task_PlayerCameraAdjustPad