---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/12/16 19:55
---

---@class Ability_Task_WeaponFireEnd : UAbleAbilityTask 武器开火结束
local Ability_Task_WeaponFireEnd = UE4.Class(nil, "Ability_Task_WeaponFireEnd")

function Ability_Task_WeaponFireEnd:OnTaskStartBP(Context)
    local Character = Context:GetOwner()
    if _SP.IsValid(Character) then
        local crtWeapon = Character:GetCrtEquipWeapon() or nil
        if _SP.IsValid(crtWeapon) then
            crtWeapon.bIsRealFiring = false
            crtWeapon.bIsFireEnd = true
            if crtWeapon.StopPetAnimation then
                crtWeapon:StopPetAnimation()
            end
        end
    end
end

return Ability_Task_WeaponFireEnd