---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/6/13 2:58
---
local Ability_Task_ChargePad = UE4.Class(nil, "Ability_Task_ChargePad")


return Ability_Task_ChargePad