---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sakuragong.
--- DateTime: 2024/5/7 15:12
---
local Ability_Task_SummonsPad = UE4.Class(nil, "Ability_Task_SummonsPad")

return Ability_Task_SummonsPad;