---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by svencgli.
--- DateTime: 2024/6/21 23:32
---
local Ability_Task_ScaleParticlePad = UE4.Class(nil, "Ability_Task_ScaleParticlePad")


return Ability_Task_ScaleParticlePad
