---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hangtian.
--- DateTime: 2024/6/19 下午3:59
---
local function ErrLog(...)
    _SP.LogError("SPAbility", "Ability_Task_AttachActorToOwner", ...)
end

local function Log(...)
    _SP.Log("SPAbility", "Ability_Task_AttachActorToOwner", ...)
end
---@class Ability_Task_ActiveHPBar
---@field Active boolean
---@field TargetType EAbleAbilityTargetType
local Ability_Task_ActiveHPBar = UE4.Class(nil, "Ability_Task_ActiveHPBar")

---@param Context UAblAbilityContext
function Ability_Task_ActiveHPBar:OnTaskStartBP(Context)
    Log("OnTaskStartBP")

end

---@param Context UAblAbilityContext
function Ability_Task_ActiveHPBar:OnTaskEndBP(Context)
    Log("OnTaskEndBP")
    ---@type SPGameMonsterBase
    local targetActor = self:GetSingleActorFromTargetTypeBP(Context, self.TargetType)
    if not targetActor then
        return
    end
    if targetActor:Cast(UE4.ASPGameMonsterBase.StaticClass()) then
        targetActor:SetHPLogicVisible(self.Active)
    end
end


return Ability_Task_ActiveHPBar