---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/2/11 16:43
---

local MeleeType = UE4.EBattleAssistCtrlWeaponType.Meleen
local GunType = UE4.EBattleAssistCtrlWeaponType.Gun
local WandType = UE4.EBattleAssistCtrlWeaponType.Wand

---@class Ability_Task_BattleAssistForceResetTarget  开启战斗镜头
local Ability_Task_BattleAssistForceResetTarget = UE4.Class(nil, "Ability_Task_BattleAssistForceResetTarget")

---OnTaskStartBP
---@param Context table
function Ability_Task_BattleAssistForceResetTarget:OnTaskStartBP(Context)
    self.bTriggered = false

    if not self:IsLocalCharacter(Context) then
        return
    end

    local character = Context:GetOwner()
    if not _SP.IsValid(character) then
        return
    end

    if not character:IsA(UE4.ASPGameCharacterBase) then
        return
    end

    local targetActor = self:GetSingleActorFromTargetTypeBP(Context, self.TargetType)
    if not _SP.IsValid(targetActor) then
        return
    end

    UE4.USPGameCameraUtils.BeginBattleAssistForceResetTarget(targetActor)
    self.bTriggered = true
end

function Ability_Task_BattleAssistForceResetTarget:OnTaskEndBP(Context)
    if self.bTriggered then
        UE4.USPGameCameraUtils.StopBattleAssistForceResetTarget()
    end
end

function Ability_Task_BattleAssistForceResetTarget:IsLocalCharacter(Context)
    if _SPFeature.Utils.WorldUtils:IsStandalone() then
        return true
    end
    local Character = Context:GetOwner()
    if Character then
        return Character:IsLocallyControlled()
    end
    return false
end

return Ability_Task_BattleAssistForceResetTarget