---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/4/26 15:13
---
local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")
local Ability_Task_PVPPlayScaleEffect = UE4.Class(nil, "Ability_Task_PVPPlayScaleEffect")
function Ability_Task_PVPPlayScaleEffect:OnTaskStartBP(Context)
    -- Get ScratchPad
    local ScratchPad = self:GetScratchPad(Context)
    if ScratchPad then
        ScratchPad.LogText = self.LogText
        print("Ability_Task_PVPPlayScaleEffect:OnTaskStartBP !!!", self.LogText)
    end

    local selfActor = Context:GetSelfActor()
    if _SP.IsValid(selfActor) and selfActor.GetMonsterID then
        local monsterID = selfActor:GetMonsterID()
        local PetPVPCfg = _SP.SPConfigManager:GetConfigById("SPPVPPetTable", "SPPVPPet", monsterID)
        if PetPVPCfg then
            if PetPVPCfg.PvpSpecialBodyTypeScale == nil then
                local PetPVPBodyType = PetPVPCfg.PvpBodyType
                local PetPVPBodyCfg= _SP.SPConfigManager:GetConfigById("SPPVPPetTable", "SPPVPPetBodyScale", PetPVPBodyType)
                if PetPVPBodyCfg and PetPVPBodyCfg.Value then
                    ScratchPad.DefalutScale = PetPVPBodyCfg.Value
                    ScratchPad.MaxScale = PetPVPBodyCfg.Value
                end
            else
                ScratchPad.DefalutScale = PetPVPCfg.PvpSpecialBodyTypeScale
                ScratchPad.MaxScale  = PetPVPCfg.PvpElementRestrainBodyTypeScale
            end
        end
    end
    ScratchPad.countTime = 0

end

local function SetScale(Context,CurrentScale)
    local Owner = Context:GetOwner()
    --local OwnerScale = Owner:GetActorScale3D()
    if Owner then
        local RootComponent = Owner:K2_GetRootComponent()
        if RootComponent then
            RootComponent:SetWorldScale3D(UE4.FVector(CurrentScale, CurrentScale, CurrentScale))
        end
    end
end

function Ability_Task_PVPPlayScaleEffect:OnTaskTickBP(Context, DeltaTime)
    local ScratchPad = self:GetScratchPad(Context)
    if not ScratchPad then
        return
    end
    if ScratchPad.countTime == nil then
        return
    end
    if ScratchPad.MaxScale == nil  or ScratchPad.DefalutScale == nil then
        return
    end

    ScratchPad.countTime = ScratchPad.countTime + DeltaTime

    local realTime = ScratchPad.countTime / self.AllTime
    if realTime > 1 then
        realTime = 1
    end

    local curveScale = self.ScaleCurve:GetFloatValue(realTime) or 1
    local currentScale

    if self.BGrow then
        currentScale = ScratchPad.DefalutScale + (ScratchPad.MaxScale - ScratchPad.DefalutScale) * curveScale
    else
        currentScale = ScratchPad.MaxScale - (ScratchPad.MaxScale - ScratchPad.DefalutScale) * curveScale
    end

    -- 使用 math.min 和 math.max 来限制 currentScale
    currentScale = math.min(currentScale, ScratchPad.MaxScale)
    currentScale = math.max(currentScale, ScratchPad.DefalutScale)
    SetScale(Context, currentScale)
end

function Ability_Task_PVPPlayScaleEffect:OnTaskEndBP(Context)
    local ScratchPad = self:GetScratchPad(Context)
    if ScratchPad then
        print("Ability_Task_PVPPlayScaleEffect:OnTaskEndBP !!!", ScratchPad.LogText)
    end
    ScratchPad.countTime = 0
    ScratchPad.DefalutScale = 0
    ScratchPad.MaxScale  = 0
end

function Ability_Task_PVPPlayScaleEffect:GetTaskScratchPadClassBP(Context)
    return SPAbilityUtils.LoadScratchPadClass(SPAbility.ScratchPadClass.PVPPlayScalePad)
end

return Ability_Task_PVPPlayScaleEffect