---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/12/17 20:42
---

---@class Ability_Task_SetPlayFireData 设置开火数据
local Ability_Task_SetPlayFireData = UE4.Class(nil, "Ability_Task_SetPlayFireData")

function Ability_Task_SetPlayFireData:OnTaskStartBP(Context)
    local Character = Context:GetOwner()
    if _SP.IsValid(Character) then
        local crtWeapon = Character:GetCrtEquipWeapon() or nil
        if _SP.IsValid(crtWeapon) then
            if crtWeapon.SetPlayFireStateData then
                crtWeapon:SetPlayFireStateData()
            end
        end
    end
end

return Ability_Task_SetPlayFireData