---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/1/23 17:16
---

local Ability_Task_WeaponMaterialEffectPad = UE4.Class(nil, "Ability_Task_WeaponMaterialEffectPad")

return Ability_Task_WeaponMaterialEffectPad