---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sakuragong.
--- DateTime: 2024/5/28 11:26
---
local SPGameAudioManager = require("Feature.StarP.Script.System.Sound.SPGameAudioManager")
--local BackpackItemClientTable = require("LetsGo.Script.TableHelper.BackpackItemClientTable")
--local SoundTable = require("LetsGo.Script.TableHelper.SoundTable")
local MoeSoundManager = require("LetsGo.Script.Core.Managers.Audio.MoeSoundManager")

local Ability_Task_Voice = UE4.Class(nil, "Ability_Task_Voice")

function Ability_Task_Voice:OnTaskStartBP(Context)
    print("Ability_Task_Voice:OnTaskStartBP")
    local ScratchPad = self:GetScratchPad(Context)
    if not ScratchPad then
        return
    end

    -- 初始化套装ID和角色ID的映射关系 对应表D_道具表_时装的id和characterID
    local InGameItemResource = _SPFeature.Config.SPAvatarSuitInGameConfig:GetAllData()
    print(InGameItemResource)
    for _, v in pairs(InGameItemResource) do
        local SuitID = tostring(v[k1])
        local CharacterId = tostring(v[k2])
        SPGameAudioManager.SuitIdCharacterIdMap[SuitID] = CharacterId
    end

    -- 初始化角色ID和SoundBank的映射关系 对应表Y_音频之人声的characterID和bank
    local CharacterSoundBank = _SPFeature.Config.EmotionVoiceConfig:GetAllData()
    for _, v in pairs(CharacterSoundBank) do
        local CharacterId = tostring(v[k1])
        local bank = tostring(v[k2])
        SPGameAudioManager.CharacterIdSoundBankMap[CharacterId] = bank
    end

    local CharacterId = self.CharacterId
    print("CharacterId is ", CharacterId)
    local ActionName = self.ActionName
    print("ActionName is ", ActionName)
    local VoiceType = self.VoiceType
    local Is3p = self.Is3p
    local Actor = Context:GetOwner()
    print("Actor is ", Actor)

    --只用于记录的变量
    local CurrAction = self.CurrAction
    local CurrPlayingID = self.CurrPlayingID
    local LastPlayTimeStamp = self.LastPlayTimeStamp

    local PlayingID = MoeSoundManager:ReceivePlayVoice(CharacterId, ActionName, VoiceType, CurrAction, CurrPlayingID, Is3p, Actor, LastPlayTimeStamp)
end

function Ability_Task_Voice:IsSingleFrameBP()
    return self.SingleFrame
end

return Ability_Task_Voice