---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created
--- DateTime: 2024/7/30 11:30
---
local Ability_Task_ChangeMaterialParameterPad = UE4.Class(nil, "Ability_Task_ChangeMaterialParameterPad")

return Ability_Task_ChangeMaterialParameterPad