---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/8/6 14:53
---

---@class Ability_Task_ConsumeFriendSkillEnergy    消耗伙伴技能能量
local Ability_Task_ConsumeFriendSkillEnergy = UE4.Class(nil, "Ability_Task_ConsumeFriendSkillEnergy")

function Ability_Task_ConsumeFriendSkillEnergy:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask","Ability_Task_ConsumeFriendSkillEnergy:OnTaskStartBP")
    local Character = self:GetPlayer(Context)
    if _SP.IsValid(Character) then
        self.WeaponInst = Character:GetCrtEquipWeapon() or nil
    end
    if _SP.IsValid(self.WeaponInst) then
        if self.IsStopConsume then
            if self.WeaponInst.DisableFireConsuming then
                self.WeaponInst:DisableFireConsuming()
            end
        else
            if self.WeaponInst.EnableFireConsuming then
                self.WeaponInst:EnableFireConsuming()
            end
        end
        if self.IsConsumeFixed then
            --自定义扣除伙伴技能能量
            if not self.WeaponInst.EnergyLogic then
                _SP.LogWarning("Ability_Task_ConsumeFriendSkillEnergy", "OnTaskStartBP self.WeaponInst.EnergyLogic is uninitialized!")
                return
            end
            self.WeaponInst.EnergyLogic:Consume(self.FixedEnergy)
        end
    end
end

function Ability_Task_ConsumeFriendSkillEnergy:OnTaskEndBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_ConsumeFriendSkillEnergy:OnTaskEndBP")
    if (not self.IsSingleFrame) and self.IsStopAtEnd and (not self.IsStopConsume)then
        if _SP.IsValid(self.WeaponInst) and self.WeaponInst.DisableFireConsuming then
            self.WeaponInst:DisableFireConsuming()
        end
    end
end

function Ability_Task_ConsumeFriendSkillEnergy:GetPlayer(Context)
    local Character = Context:GetOwner()
    if _SP.IsValid(Character) then
        if Character:Cast(UE4.ASPGameMonsterBase) then
            return Character:FindRelatedPlayerPawn()
        end
    end
    return Character
end

return Ability_Task_ConsumeFriendSkillEnergy