---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fattyyi.
--- DateTime: 2024/12/9 20:56
---
local Ability_Task_DownwardChargePad = UE4.Class(nil, "Ability_Task_DownwardChargePad")


return Ability_Task_DownwardChargePad