---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/11/20 16:06
---

local Ability_Task_WeaponFirePad = UE4.Class(nil, "Ability_Task_WeaponFirePad")

return Ability_Task_WeaponFirePad