---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ecoliwu.
--- DateTime: 2024/8/14 23:53
---

---@class Ability_Task_LaserPad : USPAbilityTaskScratchPad
local Ability_Task_LaserPad = UE4.Class(nil, "Ability_Task_LaserPad")

--[[
]]

return Ability_Task_LaserPad