---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/1/2 17:04
---

---@class Ability_Task_SummonDoSkill 召唤物执行技能(仅DS执行)
local Ability_Task_SummonDoSkill = UE4.Class(nil, "Ability_Task_SummonDoSkill")

function Ability_Task_SummonDoSkill:OnTaskStartBP(Context)
    _SP.Log("SPAbility", "Ability_Task_SummonDoSkill:OnTaskStartBP")
    local TargetArray = UE4.TArray(UE4.AActor)
    self:GetActorsForTaskBP(Context, TargetArray)
    for i = 1, TargetArray:Length() do
        local Target = TargetArray:Get(i)
        local Summoner, OwnerActor = self:GetSummoner(Target, self.SummonId)
        if Summoner and _SP.IsValid(Summoner) then
            local AbilityComp = Summoner:GetComponentByClass(UE4.USPAbilityComponent:StaticClass())
            if AbilityComp == nil then
                _SP.Log("SPAbility", "Ability_Task_SummonDoSkill:OnTaskStartBP Summoner abilityComponent is nil.")
                return
            end
            AbilityComp:InterruptActiveAbility("summon do skill.", true)
            local isSuccess = AbilityComp:TryActivateAbility(self.SkillId, OwnerActor, OwnerActor)
            if not isSuccess then
                _SP.Log("SPAbility", "Ability_Task_SummonDoSkill:OnTaskStartBP TryActivateAbility failed.")
                return
            end
        end
    end
end

function Ability_Task_SummonDoSkill:GetSummoner(Actor, SummonId)
    if _SP.IsValid(Actor) then
        local SummonInfo = _SP.SPGameAbilityManager:GetTargetSummonInfo(Actor, SummonId)
        if SummonInfo ~= nil then
            local SummonActor = SummonInfo["SummonActor"] or nil
            local OwnerActor = SummonInfo["Actor"] or nil
            return SummonActor, OwnerActor
        end
    end
    return nil
end

return Ability_Task_SummonDoSkill