---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ecoliwu.
--- DateTime: 2024/12/04 15:16
---
local Ability_Task_SaveTargetLocation = UE4.Class(nil, "Ability_Task_SaveTargetLocation")

function Ability_Task_SaveTargetLocation:OnTaskStartBP(Context)
    local targetActors = Context:GetTargetActors():ToTable()
    if #targetActors > 0 then
        -- Save the first target location
        local targetActor = targetActors[1]
        if _SP.IsValid(targetActor) then
            Context:SetTargetLocation(targetActor:K2_GetActorLocation())
        end
    end
end

function Ability_Task_SaveTargetLocation:OnTaskEndBP(Context)
end

return Ability_Task_SaveTargetLocation