---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/6/15 15:31
---

---@class Ability_Task_AttackSpeedSlow    攻击减速
local Ability_Task_AttackSpeedSlow = UE4.Class(nil, "Ability_Task_AttackSpeedSlow")

function Ability_Task_AttackSpeedSlow:OnTaskStartBP(Context)
    print("Ability_Task_AttackSpeedSlow:OnTaskStartBP")
    local Character = Context:GetOwner()
    if Character then
        local CurrentWeapon = Character:GetCrtEquipWeapon()
        if CurrentWeapon and CurrentWeapon.DecTargetSpeed then
            Character:SetPlayerSpeed(CurrentWeapon.DecTargetSpeed);
        end
    end
end

function Ability_Task_AttackSpeedSlow:OnTaskEndBP(Context)
    print("Ability_Task_AttackSpeedSlow:OnTaskEndBP")
    local Character = Context:GetOwner()
    if Character then
        Character:RecoverPlayerSpeed();
    end
end

return Ability_Task_AttackSpeedSlow