---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by actorwang.
--- DateTime: 2024/12/17 20:46
---
local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")
local SPLuaUtility = require("Feature.StarP.Script.System.SPLuaUtility")
local Ability_Task_LockSPCameraInput = UE4.Class(nil, "Ability_Task_LockSPCameraInput")

local IsValid = UE4.UKismetSystemLibrary.IsValid

function Ability_Task_LockSPCameraInput:OnTaskStartBP(Context)
    UE4.USPGameCameraUtils.CtrlMainPlayerCameraLock(true)
end

function Ability_Task_LockSPCameraInput:OnTaskEndBP(Context)
    UE4.USPGameCameraUtils.CtrlMainPlayerCameraLock(false)
end

-- function Ability_Task_LockSPCameraInput:IsSingleFrameBP()
--     return false
-- end

-- function Ability_Task_LockSPCameraInput:GetTaskRealmBP()
--     return UE4.EAbleAbilityTaskRealm.ATR_Client
-- end

return Ability_Task_LockSPCameraInput