---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/2/10 17:07
---

local Ability_Task_SetAttackType = UE4.Class(nil, "Ability_Task_SetAttackType")

function Ability_Task_SetAttackType:OnTaskStartBP(Context)
    local Character = Context:GetOwner()
    if Character then
        local InventoryComp = Character:SPGetInventoryComponent()
        if InventoryComp then
            local CrtEquipWeapon = InventoryComp:GetCrtEquipWeapon()
            if _SP.IsValid(CrtEquipWeapon) and CrtEquipWeapon:IsA(UE4.ASPComboMeleeWeapon) then
                CrtEquipWeapon:SetAttackType(self.AttackType)
            end
        end
    end
end

return Ability_Task_SetAttackType