---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/1/24 15:02
---

---@class Ability_Task_ClearLastHitActor    清除最近攻击我的敌人记录
local Ability_Task_ClearLastHitActor = UE4.Class(nil, "Ability_Task_ClearLastHitActor")

function Ability_Task_ClearLastHitActor:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask","Ability_Task_ClearLastHitActor:OnTaskStartBP")
    local Character = Context:GetOwner()
    if _SP.IsValid(Character) then
        if Character:Cast(UE4.ASPGameCharacterBase) then
            local hitComponent = Character:GetCharHitComponent()
            if hitComponent and hitComponent.ClearLastHitActor then
                hitComponent:ClearLastHitActor()
            end
        end
    end
end

return Ability_Task_ClearLastHitActor