---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fattyyi.
--- DateTime: 2024/12/2 16:11
---
local Ability_Task_PerfectDodgePad = UE4.Class(nil, "Ability_Task_PerfectDodgePad")


return Ability_Task_PerfectDodgePad