---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sakuragong.
--- DateTime: 2024/5/7 15:12
---
local Ability_Task_CameraShakePad = UE4.Class(nil, "Ability_Task_CameraShakePad")

--[[
    ---@type table<UE4.AMoeGameCharacter>
    Characters = nil
]]

return Ability_Task_CameraShakePad