---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by donglingli.
--- DateTime: 2025/1/2 14:27
---
local Ability_Task_PVPIgnoreFactionCollision = UE4.Class(nil, "Ability_Task_PVPIgnoreFactionCollision")

function Ability_Task_PVPIgnoreFactionCollision:OnTaskStartBP(Context)

end

---忽略碰撞
---@param OwnerActor UE4.ASPGameMonsterBase
---@param FactionName string
function Ability_Task_PVPIgnoreFactionCollision:IgnoreCollision(OwnerActor)
    if _SP.GameEnvType ~= UE4.ESPGameEnvType.PVP or not _SP.DS.MonsterPVPManager then
        _SP.Log("Ability_Task_PVPIgnoreFactionCollision", "current env not PVPGame")
        return
    end
    ---PVP获取友方啾灵写法
    local OwnerPlayerUID = OwnerActor:GetOwnerPlayerUID()
    local allCombatEntities = _SP.DS.MonsterPVPManager:GetCombatMonsterEntities(OwnerPlayerUID)
    for _, entity in pairs(allCombatEntities) do
        local entityActor = entity:GetActor()
        if entityActor and entityActor ~= OwnerActor then
            local Mesh = OwnerActor.Mesh
            if Mesh ~= nil then
                Mesh:IgnoreActorWhenMoving(entityActor, self.IsNeedIgnore)
            end

            local CapsuleComponent = OwnerActor.CapsuleComponent
            if CapsuleComponent ~= nil then
                CapsuleComponent:IgnoreActorWhenMoving(entityActor, self.IsNeedIgnore)
            end
        end
    end
end

function Ability_Task_PVPIgnoreFactionCollision:OnTaskTickBP(Context, DeltaTime)
    local SelfActor = Context:GetSelfActor()
    if not SelfActor then
        return
    end

    self:IgnoreCollision(SelfActor)
end

function Ability_Task_PVPIgnoreFactionCollision:OnTaskEndBP(Context, Result)
    if Result ~= UE4.EAbleAbilityTaskResult.Interrupted then
        return
    end

    local ScratchPad = self:GetScratchPad(Context)
    if not ScratchPad or not ScratchPad.Handle then
        return
    end

    ScratchPad.Handle:Abort()
    ScratchPad.Handle = nil
end

return Ability_Task_PVPIgnoreFactionCollision