---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ecoliwu.
--- DateTime: 2024/12/04 15:16
---
local Ability_Task_SaveTargetLocationPad = UE4.Class(nil, "Ability_Task_SaveTargetLocationPad")

return Ability_Task_SaveTargetLocationPad