---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/6/19 15:34
---

---@class Ability_Task_SwitchMainCameraState    切换主镜头状态
local Ability_Task_SwitchMainCameraState = UE4.Class(nil, "Ability_Task_SwitchMainCameraState")

function Ability_Task_SwitchMainCameraState:OnTaskStartBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_SwitchMainCameraState:OnTaskStartBP")
    if self.CameraName ~= "None" and self:IsLocalCharacter(Context) then
        UE4.USPGameCameraUtils.SwitchMainCameraStateByCustomParam(self.CameraName)
    end
end

function Ability_Task_SwitchMainCameraState:OnTaskEndBP(Context)
    _SP.Log("SPAbilityTask", "Ability_Task_SwitchMainCameraState:OnTaskEndBP")
    if self.bExitAtEnd and self.CameraName ~= "None" and self:IsLocalCharacter(Context) then
        UE4.USPGameCameraUtils.LeaveMainCameraStateCustomParam(self.CameraName)
    end
end

function Ability_Task_SwitchMainCameraState:IsLocalCharacter(Context)
    if _SPFeature.Utils.WorldUtils:IsStandalone() then
        return true
    end
    local Character = Context:GetOwner()
    if Character then
        return Character:IsLocallyControlled()
    end
    return false
end

return Ability_Task_SwitchMainCameraState