---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bladeyuan.
--- DateTime: 2024/6/21 19:48
---
local Ability_Task_MoveToPad = UE4.Class(nil, "Ability_Task_MoveToPad")

return Ability_Task_MoveToPad