---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by actorwang.
--- DateTime: 2024/12/17 20:46
---
local SPAbility = require("Feature.StarP.Script.System.Ability.SPAbilityClasses")
local SPAbilityUtils = require("Feature.StarP.Script.System.Ability.SPAbilityUtils")
local SPLuaUtility = require("Feature.StarP.Script.System.SPLuaUtility")
local Ability_Task_SPLerpLagCameraPostion = UE4.Class(nil, "Ability_Task_SPLerpLagCameraPostion")

local IsValid = UE4.UKismetSystemLibrary.IsValid

function Ability_Task_SPLerpLagCameraPostion:OnTaskStartBP(Context)
    if not self.LerpTime or self.LerpTime <= 0 then
        return
    end
    UE4.USPGameCameraUtils.OpenLerpLagCameraPostion(self.LerpTime)
end

function Ability_Task_SPLerpLagCameraPostion:OnTaskEndBP(Context)
    
end

return Ability_Task_SPLerpLagCameraPostion