---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/3/3 19:09
---

---@class SPInputBranchSegmentTask : UAbleAbilityTask
local SPInputBranchSegmentTask = UE4.Class(nil, "SPInputBranchSegmentTask")
local PressType = UE4.ESPTouchType.Started

function SPInputBranchSegmentTask:IsPressed(InInputTag)
    local InputManagerSubsystem = UE4.USPInputManagerSubsystem.GetInstance(_SP.GetCurrentWorld())
    if InputManagerSubsystem then
        local inputData = InputManagerSubsystem:GetInputData(InInputTag)
        --_SP.Log("SPInputBranchSegmentTask", "InputData: ", _SPFeature.MoeGameUtils.TableToString(inputData))
        if inputData and inputData.TouchType == PressType then
            return true
        end
    end
    return false
end

return SPInputBranchSegmentTask