---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2024/12/5 15:10
---

---@class SPPlayWeaponAnimationTask : UAbleAbilityTask  播放武器动画
local SPPlayWeaponAnimationTask = UE4.Class(nil, "SPPlayWeaponAnimationTask")

return SPPlayWeaponAnimationTask