---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/1/21 19:19
---

---@class SPShowTargetingUITask 显示锁定框UI、显示追踪UI
local SPShowTargetingUITask = UE4.Class(nil, "SPShowTargetingUITask")

function SPShowTargetingUITask:ShowTargetingUI(SizeX, SizeY)
    if self.UIName then
        _SPFeature.UIManager:OpenWindow(self.UIName, { SizeX = SizeX, SizeY = SizeY, Radius = self.Radius })
    end
end

function SPShowTargetingUITask:HideTargetingUI()
    if self.UIName then
        _SPFeature.UIManager:CloseWindow(self.UIName)
    end
end

function SPShowTargetingUITask:TraceActor(TraceActor, TraceData)
    _SP.Client.SPGameTargetIndicatorManager:AddRifleAimTarget(TraceActor, 10, nil, TraceData.UIName, TraceData.SocketName)
    _SP.EventManager:DispatchEvent(_SP.EventEnum.ON_SPGAME_CLIENT_TARGETING_UI_TRACE_START, TraceActor, true, TraceData.UIName)
end

function SPShowTargetingUITask:UnTraceActor(TraceActor)
    _SP.Client.SPGameTargetIndicatorManager:RemoveTargetByActor(TraceActor)
    _SP.EventManager:DispatchEvent(_SP.EventEnum.ON_SPGAME_CLIENT_TARGETING_UI_TRACE_CHANGED, nil)
end

function SPShowTargetingUITask:SendTraceEvent(bActorTraced)
    _SP.EventManager:DispatchEvent(_SP.EventEnum.ON_SPGAME_CLIENT_TARGETING_UI_TRACE_CHANGED, bActorTraced)
end

function SPShowTargetingUITask:IsLocalCharacter(Context)
    if _SPFeature.Utils.WorldUtils:IsStandalone() then
        return true
    end
    local Character = Context:GetOwner()
    if Character then
        return Character:IsLocallyControlled()
    end
    return false
end

return SPShowTargetingUITask