---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brendanwang.
--- DateTime: 2025/1/21 21:59
---

local SPShowTargetingUITaskScratchPad = UE4.Class(nil, "SPShowTargetingUITaskScratchPad")

return SPShowTargetingUITaskScratchPad