---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kaedeliang.
--- DateTime: 2025/2/20 16:06
---

---@class SPTwoInputControlTask : UAbleAbilityTask
local SPTwoInputControlTask = UE4.Class(nil, "SPTwoInputControlTask")

return SPTwoInputControlTask

